# Site settings
title: GAAP-II (Guide for Astronomers Applying to Positions in Industry)
description: > # this means to ignore newlines until "baseurl:"
  A series of online workshops for prospective postdocs in astronomy,  
  designed for senior graduate students in Canada looking to "bridge 
  the gap" toward industry and private sector postitions.  
  Organized by the Canadian Astronomical Society (CASCA) Graduate 
  Student Committee (GSC).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: CASCA Graduate Student Committee
email: cascagsc@gmail.com
facebook_username:
twitter_username:
github_username: cascagsc
address:
  - line:
  - line:
  # Feel free to add more lines here
copyright: CASCA Graduate Student Committee

# API settings
google_api_key:

# Build settings
markdown: kramdown
